version: '3.8'

services:
    ecommerce-nginx:
        container_name: ecommerce-nginx
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "8080:80"
        links:
            - ecommerce-php
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOST}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOST}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - ecommerce

    ecommerce-php:
         container_name: ecommerce-php
         restart: unless-stopped
         user: ${USER_ID}:${GROUP_ID}
         build:
            context: ./
            dockerfile: docker/php/Dockerfile
            args:
                PHP_BASE_IMAGE: ${PHP_BASE_IMAGE}
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                NODE_VERSION: ${NODE_VERSION}
         volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
         links: 
            - ecommerce-mysql
            - ecommerce-redis
         ports:
            - "9001:9001"
         tmpfs:
            - /dev/shm
         networks:
            - ecommerce
         extra_hosts:
            - "host.docker.internal:host-gateway"
         
    ecommerce-mysql:
          container_name: ecommerce-mysql
          restart: unless-stopped
          image: mysql:8.0.31
          volumes: 
            - ./docker/mysql/mysql.conf:/etc/mysql/conf.d/mysql.conf
          command: --default-authentication-plugin=mysql_native_password
          environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
          ports:
            - ${MYSQL_EXTERNAL_PORT}:3306
          networks:
            - ecommerce

    ecommerce-redis:
          container_name:  ecommerce-redis
          restart: unless-stopped
          build:
            context: ./
            dockerfile: docker/redis/Dockerfile
            args:
                REDIS_PASSWORD: ${REDIS_PASSWORD}
          ports:
              - ${REDIS_EXTERNAL_PORT}:6379
          sysctls:
              - net.core.somaxconn=511
          networks:
            - ecommerce

    ecommerce-vite:
        container_name: ecommerce-vite
        restart: unless-stopped
        build:
            context: ./
            dockerfile: docker/vite/Dockerfile
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        ports:
            - "5173:5173"
        environment:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
        networks:
            - ecommerce

networks:
    ecommerce: 
    nginx-proxy:
      external: true
